from __future__ import annotations

import json
from pathlib import Path

from can_diag.decoder import NetworkDatabase
from can_diag.logfile import MalformedLine
from can_diag.monitor import analyze_frames
from can_diag.reporting import (
    GLOBAL_LIMITATIONS,
    build_report,
    render_markdown,
    write_json_report,
    write_markdown_report,
)
from tests.conftest import (
    POWER_DATA_ID,
    THERMAL_DATA_ID,
    THERMAL_HEARTBEAT_ID,
    data_frame,
    data_payload,
    frame,
    healthy_stream,
    heartbeat_frame,
)

REQUIRED_EVENT_FIELDS = {
    "timestamp",
    "classification",
    "node",
    "can_id",
    "message_name",
    "summary",
    "observed_evidence",
    "configured_expectation",
    "recovery_seconds",
    "limitation",
}


def eventful_frames() -> list:
    frames = [
        data_frame(0.0, POWER_DATA_ID, 0),
        frame(0.02, THERMAL_DATA_ID, data_payload(0x7FFF, 1240, 2, 0, 1)),
        heartbeat_frame(0.05, THERMAL_HEARTBEAT_ID, 5),
        data_frame(0.1, POWER_DATA_ID, 1),
        data_frame(0.2, POWER_DATA_ID, 2),
        data_frame(5.0, POWER_DATA_ID, 3),
    ]
    return sorted(frames, key=lambda item: item.timestamp)


def build(database: NetworkDatabase, frames: list, name: str = "fault_session.log"):
    monitor = analyze_frames(database, frames)
    return build_report(
        monitor=monitor,
        capture_name=name,
        dbc_name="hobby_network.dbc",
        data_origin="synthetic capture generated by can_diag.synthetic",
    )


def test_report_of_healthy_traffic_has_no_events(database: NetworkDatabase) -> None:
    report = build(database, healthy_stream(5.0), "normal_session.log")
    assert report.events == []
    assert report.event_counts() == {}
    assert "No diagnostic events were raised" in render_markdown(report)


def test_json_report_structure(database: NetworkDatabase, tmp_path: Path) -> None:
    report = build(database, eventful_frames())
    path = write_json_report(report, tmp_path / "report.json")
    payload = json.loads(path.read_text(encoding="utf-8"))

    assert payload["tool"] == "can-diag"
    assert payload["capture"]["name"] == "fault_session.log"
    assert payload["capture"]["database"] == "hobby_network.dbc"
    assert payload["capture"]["data_origin"].startswith("synthetic")
    assert payload["capture"]["frame_count"] == len(eventful_frames())
    assert payload["configuration"]["data_stale_ms"] == 350
    assert payload["configuration"]["heartbeat_stale_ms"] == 2500
    assert payload["limitations"] == list(GLOBAL_LIMITATIONS)
    assert len(payload["messages"]) == 4
    assert payload["events"]

    for event in payload["events"]:
        assert REQUIRED_EVENT_FIELDS.issubset(event)
        assert event["severity"] in {"critical", "major", "minor", "info"}
        assert event["observed_evidence"]
        assert event["configured_expectation"]
        assert event["limitation"]


def test_markdown_report_sections(database: NetworkDatabase, tmp_path: Path) -> None:
    report = build(database, eventful_frames())
    path = write_markdown_report(report, tmp_path / "report.md")
    text = path.read_text(encoding="utf-8")

    assert text.startswith("# CAN diagnostic report: fault_session.log")
    for heading in (
        "## Capture summary",
        "## Configured expectations",
        "## Event totals",
        "## Diagnostic events",
        "## Limitations",
    ):
        assert heading in text

    assert "**Observed evidence:**" in text
    assert "**Configured expectation:**" in text
    assert "**Limitation:**" in text
    assert "**Recovery time:**" in text
    for limitation in GLOBAL_LIMITATIONS:
        assert limitation in text


def test_report_records_malformed_lines_and_unknown_identifiers(
    database: NetworkDatabase, tmp_path: Path
) -> None:
    frames = eventful_frames() + [data_frame(0.3, 0x555, 0)]
    monitor = analyze_frames(database, sorted(frames, key=lambda item: item.timestamp))
    report = build_report(
        monitor=monitor,
        capture_name="session.log",
        dbc_name="hobby_network.dbc",
        data_origin="origin not declared by capture location",
        malformed=[MalformedLine(4, "garbage", "line does not match the expected format")],
    )
    payload = json.loads(write_json_report(report, tmp_path / "r.json").read_text(encoding="utf-8"))
    assert payload["unknown_ids"] == {"0x555": 1}
    assert payload["malformed_lines"][0]["line_number"] == 4
    assert payload["capture"]["malformed_line_count"] == 1

    text = render_markdown(report)
    assert "## Undecodable identifiers" in text
    assert "## Malformed capture lines" in text


def test_localization_wording_for_a_silent_node(database: NetworkDatabase) -> None:
    from tests.test_freshness import outage_stream

    report = build(database, outage_stream(30.0, 33.0, 40.0))
    silent = [event for event in report.events if event.kind.value == "node_silent"]
    assert len(silent) == 1
    text = f"{silent[0].evidence} {silent[0].limitation}"
    assert "THERMAL_DATA" in text
    assert "THERMAL_HEARTBEAT" in text
    assert "PowerMonitor" in text
    assert "localizes the communication interruption to ThermalController" in text
    assert (
        "cannot distinguish firmware, power, wiring, transceiver, or bus-controller failure" in text
    )


def test_severity_ranking_marks_recoveries_as_informational(database: NetworkDatabase) -> None:
    report = build(database, eventful_frames())
    informational = {
        event.kind.value for event in report.events if event not in report.alert_events()
    }
    assert informational.issubset({"message_recovered", "node_recovered", "range_recovered"})
