from __future__ import annotations

import argparse
import json
import sys
import time
from collections.abc import Sequence
from pathlib import Path

from can_diag import __version__
from can_diag.config import AnalyzerConfig, ConfigError, load_config
from can_diag.decoder import DecodeError, NetworkDatabase
from can_diag.logfile import LogReadResult, read_log
from can_diag.models import CanFrame, DiagnosticEvent, UnknownFrame
from can_diag.monitor import DiagnosticMonitor, analyze_frames
from can_diag.recorder import (
    DEFAULT_BITRATE,
    DEFAULT_INTERFACE,
    BusError,
    open_bus,
    record_to_file,
)
from can_diag.replay import ReplayError, channel_is_virtual, physical_channel_warning, replay_frames
from can_diag.reporting import (
    build_report,
    render_markdown,
    write_json_report,
    write_markdown_report,
)
from can_diag.timing import compare_captures

DEFAULT_DBC = Path("dbc/hobby_network.dbc")
EXIT_OK = 0
EXIT_FAILURE = 1


class CommandError(Exception):
    pass


def _resolve_config(arguments: argparse.Namespace) -> AnalyzerConfig:
    config = load_config(getattr(arguments, "config", None))
    return config.with_overrides(
        data_stale_ms=getattr(arguments, "data_stale_ms", None),
        heartbeat_stale_ms=getattr(arguments, "heartbeat_stale_ms", None),
    )


def _load_database(path: Path) -> NetworkDatabase:
    return NetworkDatabase.load(path)


def _read_capture(path: Path) -> LogReadResult:
    result = read_log(path)
    if result.malformed:
        for item in result.malformed[:10]:
            print(
                f"warning: skipping malformed line {item.line_number}: {item.reason}",
                file=sys.stderr,
            )
        if len(result.malformed) > 10:
            print(
                f"warning: {len(result.malformed) - 10} further malformed lines were skipped",
                file=sys.stderr,
            )
    return result


def _data_origin(path: Path) -> str:
    parts = {part.lower() for part in path.parts}
    if "synthetic" in parts:
        return "synthetic capture generated by can_diag.synthetic"
    if "hardware" in parts:
        return "hardware capture recorded from a physical CAN interface"
    return "origin not declared by capture location"


def _format_signals(frame_signals: Sequence[object]) -> str:
    rendered = []
    for signal in frame_signals:
        rendered.append(f"{signal.name}={signal.format_value()}")
    return ", ".join(rendered)


def _print_event(event: DiagnosticEvent, origin: float | None) -> None:
    relative = event.timestamp if origin is None else event.timestamp - origin
    identifier = "  n/a" if event.arbitration_id is None else f"0x{event.arbitration_id:03X}"
    print(
        f"[t+{relative:8.3f}] {event.kind.value:<20} {identifier} {event.node:<18} {event.summary}"
    )
    print(f"             evidence: {event.evidence}")
    print(f"             expected: {event.expectation}")
    if event.recovery_seconds is not None:
        print(f"             recovery: {event.recovery_seconds:.3f} s")
    print(f"             limitation: {event.limitation}")


def command_decode(arguments: argparse.Namespace) -> int:
    database = _load_database(arguments.dbc)
    capture = _read_capture(arguments.input)
    if not capture.frames:
        print(f"no CAN frames found in {arguments.input.name}", file=sys.stderr)
        return EXIT_OK if arguments.allow_empty else EXIT_FAILURE

    origin = capture.frames[0].timestamp
    wanted = set(arguments.can_id or [])
    shown = 0
    unknown_ids: dict[int, int] = {}
    for frame in capture.frames:
        if wanted and frame.arbitration_id not in wanted:
            continue
        if arguments.limit is not None and shown >= arguments.limit:
            break
        decoded = database.decode(frame)
        relative = frame.timestamp - origin
        if isinstance(decoded, UnknownFrame):
            unknown_ids[frame.arbitration_id] = unknown_ids.get(frame.arbitration_id, 0) + 1
            print(
                f"t+{relative:8.3f}  0x{frame.arbitration_id:03X}  "
                f"{'<unknown>':<18} {'<unknown>':<18} raw={frame.hex_data}"
            )
        else:
            print(
                f"t+{relative:8.3f}  0x{frame.arbitration_id:03X}  "
                f"{decoded.message_name:<18} {decoded.sender:<18} "
                f"{_format_signals(decoded.signals)}"
            )
        shown += 1

    print("")
    print(f"frames displayed: {shown} of {len(capture.frames)}")
    if unknown_ids:
        listed = ", ".join(f"0x{key:03X} ({value})" for key, value in sorted(unknown_ids.items()))
        print(f"identifiers absent from the database: {listed}")
    if capture.malformed:
        print(f"malformed lines skipped: {len(capture.malformed)}")
    return EXIT_OK


def command_monitor(arguments: argparse.Namespace) -> int:
    database = _load_database(arguments.dbc)
    config = _resolve_config(arguments)
    monitor = DiagnosticMonitor(database, config)

    try:
        bus = open_bus(arguments.channel, arguments.interface, arguments.bitrate)
    except BusError as error:
        raise CommandError(str(error)) from error

    print(f"monitoring {arguments.channel} using backend {arguments.interface}")
    print(
        f"data stale threshold {config.data_stale_ms} ms, "
        f"heartbeat stale threshold {config.heartbeat_stale_ms} ms"
    )
    print("press Ctrl+C to stop")

    started = time.monotonic()
    origin: float | None = None
    try:
        while True:
            if arguments.duration is not None and time.monotonic() - started >= arguments.duration:
                break
            message = bus.recv(timeout=0.1)
            now = time.time()
            if message is None:
                for event in monitor.finalize(until=now):
                    _print_event(event, origin)
                continue
            if message.is_error_frame or message.is_remote_frame:
                continue
            frame = CanFrame(
                timestamp=float(message.timestamp),
                arbitration_id=int(message.arbitration_id),
                data=bytes(message.data or b""),
                channel=arguments.channel,
                is_extended_id=bool(message.is_extended_id),
            )
            if origin is None:
                origin = frame.timestamp
            events = monitor.process_frame(frame)
            if arguments.show_frames:
                decoded = database.decode(frame)
                name = "<unknown>" if isinstance(decoded, UnknownFrame) else decoded.message_name
                print(f"t+{frame.timestamp - origin:8.3f}  0x{frame.arbitration_id:03X}  {name}")
            for event in events:
                _print_event(event, origin)
    except KeyboardInterrupt:
        print("")
        print("monitor stopped by user")
    finally:
        bus.shutdown()

    for event in monitor.finalize(until=time.time()):
        _print_event(event, origin)

    print("")
    print(f"frames observed: {monitor.frame_count}")
    print(f"diagnostic events: {len(monitor.events)}")
    return EXIT_OK


def command_record(arguments: argparse.Namespace) -> int:
    output = arguments.output
    if output.exists() and not arguments.overwrite:
        raise CommandError(
            f"{output.name} already exists. Pass --overwrite to replace the existing capture."
        )
    print(f"recording {arguments.channel} using backend {arguments.interface}")
    if arguments.duration is None:
        print("press Ctrl+C to stop recording")
    try:
        result = record_to_file(
            channel=arguments.channel,
            output_path=output,
            interface=arguments.interface,
            bitrate=arguments.bitrate,
            duration_seconds=arguments.duration,
        )
    except BusError as error:
        raise CommandError(str(error)) from error

    if result.frame_count == 0:
        raise CommandError(
            f"no frames were received on {arguments.channel}. An empty capture was written to "
            f"{output.name}; verify wiring, bitrate, and termination before retrying."
        )
    print(f"wrote {result.frame_count} frames to {output.name} in {result.duration_seconds:.3f} s")
    return EXIT_OK


def command_replay(arguments: argparse.Namespace) -> int:
    capture = _read_capture(arguments.input)
    if not capture.frames:
        raise CommandError(f"{arguments.input.name} contains no replayable frames")

    if not channel_is_virtual(arguments.channel):
        print(f"warning: {physical_channel_warning(arguments.channel)}", file=sys.stderr)
        if not arguments.allow_physical:
            raise CommandError(
                "refusing to replay onto a non-virtual channel without --allow-physical"
            )

    try:
        result = replay_frames(
            frames=capture.frames,
            channel=arguments.channel,
            interface=arguments.interface,
            bitrate=arguments.bitrate,
            speed_factor=arguments.speed,
        )
    except ReplayError as error:
        raise CommandError(str(error)) from error

    print(
        f"replayed {result.frames_sent} frames onto {result.channel} "
        f"in {result.wall_clock_seconds:.3f} s "
        f"(capture span {result.capture_span_seconds:.3f} s)"
    )
    return EXIT_OK


def command_report(arguments: argparse.Namespace) -> int:
    database = _load_database(arguments.dbc)
    config = _resolve_config(arguments)
    capture = _read_capture(arguments.input)
    if not capture.frames and not arguments.allow_empty:
        raise CommandError(f"{arguments.input.name} contains no CAN frames to analyze")

    monitor = analyze_frames(database, capture.frames, config)
    report = build_report(
        monitor=monitor,
        capture_name=arguments.input.name,
        dbc_name=arguments.dbc.name,
        data_origin=_data_origin(arguments.input),
        malformed=capture.malformed,
    )

    json_path = arguments.json_output or arguments.input.with_suffix(".report.json")
    markdown_path = arguments.markdown_output or arguments.input.with_suffix(".report.md")
    write_json_report(report, json_path)
    write_markdown_report(report, markdown_path)

    print(f"analyzed {report.summary.frame_count} frames from {report.summary.capture_name}")
    print(f"diagnostic events: {len(report.events)} ({len(report.alert_events())} above info)")
    for kind, count in report.event_counts().items():
        print(f"  {kind}: {count}")
    print(f"json report: {json_path.name}")
    print(f"markdown report: {markdown_path.name}")

    if arguments.print_markdown:
        print("")
        print(render_markdown(report))

    if arguments.fail_on_alert and report.alert_events():
        return EXIT_FAILURE
    return EXIT_OK


def command_verify_replay(arguments: argparse.Namespace) -> int:
    database = _load_database(arguments.dbc)
    config = _resolve_config(arguments)
    original = _read_capture(arguments.original)
    replayed = _read_capture(arguments.replayed)
    if not original.frames or not replayed.frames:
        raise CommandError("both captures must contain at least one frame")

    comparison = compare_captures(database, original.frames, replayed.frames, config)
    print(f"original frames: {comparison.original_frame_count}")
    print(f"replayed frames: {comparison.replayed_frame_count}")
    print(f"identifier order preserved: {comparison.identifier_order_matches}")
    print(f"payloads identical: {comparison.payloads_match}")
    print(f"exact id and payload match: {comparison.exact_match_percent:.3f} %")
    print(f"sequence continuity preserved: {comparison.sequence_continuity_matches}")
    print(f"event classifications equal: {comparison.event_classifications_match}")
    print(f"median absolute relative timing error: {comparison.timing.median_abs_error_ms:.3f} ms")
    print(f"95th percentile timing error: {comparison.timing.p95_abs_error_ms:.3f} ms")
    print(f"maximum timing error: {comparison.timing.max_abs_error_ms:.3f} ms")
    if comparison.first_mismatch_index is not None:
        print(f"first mismatching frame index: {comparison.first_mismatch_index}")

    if arguments.json_output is not None:
        arguments.json_output.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            "original_capture": arguments.original.name,
            "replayed_capture": arguments.replayed.name,
            "database": arguments.dbc.name,
            **comparison.to_dict(),
        }
        arguments.json_output.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
        print(f"json summary: {arguments.json_output.name}")

    return EXIT_OK if comparison.passed else EXIT_FAILURE


def _add_threshold_options(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--config", type=Path, help="JSON or TOML file with analyzer thresholds")
    parser.add_argument(
        "--data-stale-ms", type=int, help="freshness threshold for cyclic data messages"
    )
    parser.add_argument(
        "--heartbeat-stale-ms", type=int, help="freshness threshold for heartbeat messages"
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="can-diag",
        description=(
            "Decode, monitor, record, replay and diagnose traffic on an isolated hobby CAN bench."
        ),
    )
    parser.add_argument("--version", action="version", version=f"can-diag {__version__}")
    subparsers = parser.add_subparsers(dest="command", required=True)

    decode = subparsers.add_parser("decode", help="decode a candump compatible capture")
    decode.add_argument("--dbc", type=Path, default=DEFAULT_DBC)
    decode.add_argument("--input", type=Path, required=True)
    decode.add_argument("--limit", type=int, help="stop after this many displayed frames")
    decode.add_argument(
        "--can-id",
        type=lambda value: int(value, 0),
        action="append",
        help="only display this identifier, may be repeated",
    )
    decode.add_argument("--allow-empty", action="store_true")
    decode.set_defaults(handler=command_decode)

    monitor = subparsers.add_parser("monitor", help="monitor a live SocketCAN or virtual interface")
    monitor.add_argument("--dbc", type=Path, default=DEFAULT_DBC)
    monitor.add_argument("--channel", required=True)
    monitor.add_argument("--interface", default=DEFAULT_INTERFACE)
    monitor.add_argument("--bitrate", type=int, default=DEFAULT_BITRATE)
    monitor.add_argument("--duration", type=float, help="stop after this many seconds")
    monitor.add_argument("--show-frames", action="store_true")
    _add_threshold_options(monitor)
    monitor.set_defaults(handler=command_monitor)

    record = subparsers.add_parser("record", help="record a live interface to a replayable log")
    record.add_argument("--channel", required=True)
    record.add_argument("--interface", default=DEFAULT_INTERFACE)
    record.add_argument("--bitrate", type=int, default=DEFAULT_BITRATE)
    record.add_argument("--output", type=Path, required=True)
    record.add_argument("--duration", type=float, help="stop after this many seconds")
    record.add_argument("--overwrite", action="store_true")
    record.set_defaults(handler=command_record)

    replay = subparsers.add_parser("replay", help="replay a capture onto an explicit channel")
    replay.add_argument("--input", type=Path, required=True)
    replay.add_argument("--channel", required=True)
    replay.add_argument("--interface", default=DEFAULT_INTERFACE)
    replay.add_argument("--bitrate", type=int, default=DEFAULT_BITRATE)
    replay.add_argument("--speed", type=float, default=1.0)
    replay.add_argument("--allow-physical", action="store_true")
    replay.set_defaults(handler=command_replay)

    report = subparsers.add_parser("report", help="write JSON and Markdown diagnostic reports")
    report.add_argument("--dbc", type=Path, default=DEFAULT_DBC)
    report.add_argument("--input", type=Path, required=True)
    report.add_argument("--json-output", type=Path)
    report.add_argument("--markdown-output", type=Path)
    report.add_argument("--print-markdown", action="store_true")
    report.add_argument("--fail-on-alert", action="store_true")
    report.add_argument("--allow-empty", action="store_true")
    _add_threshold_options(report)
    report.set_defaults(handler=command_report)

    verify = subparsers.add_parser("verify-replay", help="compare an original and replayed capture")
    verify.add_argument("--dbc", type=Path, default=DEFAULT_DBC)
    verify.add_argument("--original", type=Path, required=True)
    verify.add_argument("--replayed", type=Path, required=True)
    verify.add_argument("--json-output", type=Path)
    _add_threshold_options(verify)
    verify.set_defaults(handler=command_verify_replay)

    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    arguments = parser.parse_args(argv)
    try:
        return int(arguments.handler(arguments))
    except (CommandError, ConfigError, DecodeError, ReplayError, BusError) as error:
        print(f"error: {error}", file=sys.stderr)
        return EXIT_FAILURE
    except FileNotFoundError as error:
        print(f"error: {error}", file=sys.stderr)
        return EXIT_FAILURE


if __name__ == "__main__":
    raise SystemExit(main())
