from __future__ import annotations

import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from can_diag import __version__
from can_diag.config import AnalyzerConfig
from can_diag.logfile import MalformedLine
from can_diag.models import DiagnosticEvent, EventKind
from can_diag.monitor import DiagnosticMonitor

GLOBAL_LIMITATIONS: tuple[str, ...] = (
    "A missing or stale message proves that expected traffic stopped reaching the analyzer. "
    "It does not prove the physical root cause.",
    "Signal ranges in the DBC are project-defined plausibility limits for this bench, not "
    "manufacturer specifications.",
    "Replay reproduces captured application frames and approximate relative timing. It does not "
    "reproduce electrical noise, arbitration behaviour, error frames, or other physical-layer "
    "conditions.",
    "Captures stored under data/synthetic are generated by the deterministic dataset generator. "
    "They are not production-vehicle data and were not recorded from hardware.",
)

EVENT_SEVERITY: Mapping[EventKind, str] = {
    EventKind.NODE_SILENT: "critical",
    EventKind.HEARTBEAT_TIMEOUT: "critical",
    EventKind.DATA_MESSAGE_STALE: "major",
    EventKind.RANGE_VIOLATION: "major",
    EventKind.SEQUENCE_GAP: "minor",
    EventKind.UNKNOWN_MESSAGE_ID: "minor",
    EventKind.NODE_RESTART: "major",
    EventKind.MESSAGE_RECOVERED: "info",
    EventKind.NODE_RECOVERED: "info",
    EventKind.RANGE_RECOVERED: "info",
}


@dataclass(frozen=True)
class CaptureSummary:
    capture_name: str
    dbc_name: str
    frame_count: int
    malformed_line_count: int
    duration_seconds: float
    first_timestamp: float | None
    last_timestamp: float | None
    data_origin: str


@dataclass
class AnalysisReport:
    summary: CaptureSummary
    config: AnalyzerConfig
    events: list[DiagnosticEvent]
    per_message: list[dict[str, Any]]
    unknown_ids: dict[int, int]
    malformed: list[MalformedLine] = field(default_factory=list)

    def event_counts(self) -> dict[str, int]:
        counts: dict[str, int] = {}
        for event in self.events:
            counts[event.kind.value] = counts.get(event.kind.value, 0) + 1
        return dict(sorted(counts.items()))

    def alert_events(self) -> list[DiagnosticEvent]:
        return [event for event in self.events if EVENT_SEVERITY.get(event.kind, "info") != "info"]

    def to_dict(self) -> dict[str, Any]:
        return {
            "tool": "can-diag",
            "tool_version": __version__,
            "capture": {
                "name": self.summary.capture_name,
                "database": self.summary.dbc_name,
                "data_origin": self.summary.data_origin,
                "frame_count": self.summary.frame_count,
                "malformed_line_count": self.summary.malformed_line_count,
                "duration_seconds": round(self.summary.duration_seconds, 6),
                "first_timestamp": self.summary.first_timestamp,
                "last_timestamp": self.summary.last_timestamp,
            },
            "configuration": self.config.to_dict(),
            "event_counts": self.event_counts(),
            "alert_count": len(self.alert_events()),
            "events": [
                {**event.to_dict(), "severity": EVENT_SEVERITY.get(event.kind, "info")}
                for event in self.events
            ],
            "messages": self.per_message,
            "unknown_ids": {
                f"0x{identifier:03X}": count
                for identifier, count in sorted(self.unknown_ids.items())
            },
            "malformed_lines": [
                {"line_number": item.line_number, "reason": item.reason} for item in self.malformed
            ],
            "limitations": list(GLOBAL_LIMITATIONS),
        }


def build_report(
    monitor: DiagnosticMonitor,
    capture_name: str,
    dbc_name: str,
    data_origin: str,
    malformed: Sequence[MalformedLine] = (),
) -> AnalysisReport:
    first = monitor.first_timestamp
    last = monitor.last_timestamp
    duration = 0.0 if first is None or last is None else last - first
    per_message: list[dict[str, Any]] = []
    for name, state in sorted(monitor.message_states().items()):
        threshold = monitor.config.stale_threshold_seconds(name, state.info.is_heartbeat)
        per_message.append(
            {
                "message_name": name,
                "can_id": f"0x{state.info.frame_id:03X}",
                "sender": state.info.sender,
                "cycle_time_ms": state.info.cycle_time_ms,
                "stale_threshold_ms": round(threshold * 1000, 3),
                "frames_observed": state.frame_count,
                "last_timestamp": (
                    None if state.last_timestamp is None else round(state.last_timestamp, 6)
                ),
            }
        )
    return AnalysisReport(
        summary=CaptureSummary(
            capture_name=capture_name,
            dbc_name=dbc_name,
            frame_count=monitor.frame_count,
            malformed_line_count=len(malformed),
            duration_seconds=duration,
            first_timestamp=None if first is None else round(first, 6),
            last_timestamp=None if last is None else round(last, 6),
            data_origin=data_origin,
        ),
        config=monitor.config,
        events=monitor.events,
        per_message=per_message,
        unknown_ids=monitor.unknown_ids,
        malformed=list(malformed),
    )


def write_json_report(report: AnalysisReport, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(report.to_dict(), indent=2, sort_keys=False) + "\n", encoding="utf-8"
    )
    return path


def _relative(timestamp: float, origin: float | None) -> str:
    if origin is None:
        return f"{timestamp:.3f}"
    return f"{timestamp - origin:.3f}"


def render_markdown(report: AnalysisReport) -> str:
    origin = report.summary.first_timestamp
    lines: list[str] = []
    lines.append(f"# CAN diagnostic report: {report.summary.capture_name}")
    lines.append("")
    lines.append(
        f"Produced by can-diag {__version__} from `{report.summary.capture_name}`. "
        "Regenerate with `python scripts/regenerate.py`."
    )
    lines.append("")
    lines.append("## Capture summary")
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("| --- | --- |")
    lines.append(f"| Capture | `{report.summary.capture_name}` |")
    lines.append(f"| Database | `{report.summary.dbc_name}` |")
    lines.append(f"| Data origin | {report.summary.data_origin} |")
    lines.append(f"| Frames analyzed | {report.summary.frame_count} |")
    lines.append(f"| Malformed lines skipped | {report.summary.malformed_line_count} |")
    lines.append(f"| Capture duration | {report.summary.duration_seconds:.3f} s |")
    lines.append(f"| Diagnostic events | {len(report.events)} |")
    lines.append(f"| Events above informational severity | {len(report.alert_events())} |")
    lines.append("")

    lines.append("## Configured expectations")
    lines.append("")
    lines.append("| Message | CAN ID | Sender | Cycle time | Stale after | Frames observed |")
    lines.append("| --- | --- | --- | --- | --- | --- |")
    for entry in report.per_message:
        cycle = "unspecified" if entry["cycle_time_ms"] is None else f"{entry['cycle_time_ms']} ms"
        lines.append(
            f"| {entry['message_name']} | {entry['can_id']} | {entry['sender']} | {cycle} | "
            f"{entry['stale_threshold_ms']:.0f} ms | {entry['frames_observed']} |"
        )
    lines.append("")

    counts = report.event_counts()
    lines.append("## Event totals")
    lines.append("")
    if not counts:
        lines.append("No diagnostic events were raised for this capture.")
    else:
        lines.append("| Classification | Count |")
        lines.append("| --- | --- |")
        for name, count in counts.items():
            lines.append(f"| {name} | {count} |")
    lines.append("")

    lines.append("## Diagnostic events")
    lines.append("")
    if not report.events:
        lines.append("No diagnostic events were raised for this capture.")
        lines.append("")
    for index, event in enumerate(report.events, start=1):
        identifier = "n/a" if event.arbitration_id is None else f"0x{event.arbitration_id:03X}"
        name = event.message_name or "n/a"
        severity = EVENT_SEVERITY.get(event.kind, "info")
        lines.append(
            f"### {index}. t+{_relative(event.timestamp, origin)} s "
            f"| {event.kind.value} | {event.node}"
        )
        lines.append("")
        lines.append(f"- **Severity:** {severity}")
        lines.append(f"- **Absolute timestamp:** {event.timestamp:.6f}")
        lines.append(f"- **Node:** {event.node}")
        lines.append(f"- **CAN ID:** {identifier}")
        lines.append(f"- **Message:** {name}")
        lines.append(f"- **Classification:** {event.kind.value}")
        lines.append(f"- **Summary:** {event.summary}")
        lines.append(f"- **Observed evidence:** {event.evidence}")
        lines.append(f"- **Configured expectation:** {event.expectation}")
        if event.recovery_seconds is not None:
            lines.append(f"- **Recovery time:** {event.recovery_seconds:.3f} s")
        else:
            lines.append("- **Recovery time:** not applicable for this event")
        lines.append(f"- **Limitation:** {event.limitation}")
        lines.append("")

    if report.unknown_ids:
        lines.append("## Undecodable identifiers")
        lines.append("")
        lines.append("| CAN ID | Frames |")
        lines.append("| --- | --- |")
        for identifier, count in sorted(report.unknown_ids.items()):
            lines.append(f"| 0x{identifier:03X} | {count} |")
        lines.append("")

    if report.malformed:
        lines.append("## Malformed capture lines")
        lines.append("")
        lines.append("| Line | Reason |")
        lines.append("| --- | --- |")
        for item in report.malformed:
            lines.append(f"| {item.line_number} | {item.reason} |")
        lines.append("")

    lines.append("## Limitations")
    lines.append("")
    for item in GLOBAL_LIMITATIONS:
        lines.append(f"- {item}")
    lines.append("")
    return "\n".join(lines)


def write_markdown_report(report: AnalysisReport, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_markdown(report), encoding="utf-8", newline="\n")
    return path
