from __future__ import annotations

import argparse
import sys
from pathlib import Path

from can_diag.decoder import DecodeError, NetworkDatabase
from can_diag.monitor import analyze_frames
from can_diag.reporting import build_report, write_json_report, write_markdown_report
from can_diag.scenario import ALL_SCENARIOS
from can_diag.synthetic import generate_capture, write_capture

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DBC = ROOT / "dbc" / "hobby_network.dbc"
DEFAULT_DATA_DIR = ROOT / "data" / "synthetic"
DEFAULT_REPORT_DIR = ROOT / "reports"
SYNTHETIC_ORIGIN = "synthetic capture generated by can_diag.synthetic"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Regenerate every committed artifact: the synthetic captures, their ground truth, "
            "and the JSON and Markdown diagnostic reports. Output is deterministic, so a clean "
            "checkout that runs this command sees no file change."
        )
    )
    parser.add_argument("--dbc", type=Path, default=DEFAULT_DBC)
    parser.add_argument("--data-dir", type=Path, default=DEFAULT_DATA_DIR)
    parser.add_argument("--report-dir", type=Path, default=DEFAULT_REPORT_DIR)
    arguments = parser.parse_args(argv)

    try:
        database = NetworkDatabase.load(arguments.dbc)
    except DecodeError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    arguments.data_dir.mkdir(parents=True, exist_ok=True)
    arguments.report_dir.mkdir(parents=True, exist_ok=True)

    for scenario in ALL_SCENARIOS:
        capture = generate_capture(database, scenario)
        log_path, truth_path = write_capture(capture, arguments.data_dir)

        monitor = analyze_frames(database, capture.frames)
        report = build_report(
            monitor=monitor,
            capture_name=log_path.name,
            dbc_name=arguments.dbc.name,
            data_origin=SYNTHETIC_ORIGIN,
        )
        json_path = write_json_report(report, arguments.report_dir / f"{scenario.name}.json")
        markdown_path = write_markdown_report(report, arguments.report_dir / f"{scenario.name}.md")

        counts = report.event_counts()
        summary = ", ".join(f"{name}={count}" for name, count in counts.items()) or "no findings"
        print(f"{scenario.name}: {len(capture.frames)} frames, {summary}")
        for path in (log_path, truth_path, json_path, markdown_path):
            print(f"  wrote {path.relative_to(ROOT).as_posix()}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
